version: '3.1'

services:

  mysql:
    build: .
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8123:8080
    environment:
      ADMINER_DEFAULT_SERVER: mysql